/* eslint-disable */
/*
 * This file is autogenerated. DO NOT MODIFY BY HAND!
 * Run the @clutch-sh/tools registerWorkflows target instead
*/
import { default as clutchShEc2} from "@clutch-sh/ec2";
import { default as clutchCustomGatewayEcho} from "@clutch-custom-gateway/echo";

const registeredWorkflows = {
  "@clutch-sh/ec2": clutchShEc2,
  "@clutch-custom-gateway/echo": clutchCustomGatewayEcho,
};
export default registeredWorkflows;